### ISSUE TITLE
Request help installation 

### ISSUE THREAD

**Issue by Marr575** [barbagroup/pygbe#74]
Hello, I’m interested in use Pygbe to study the orientation of one ezyme on the surface of one electrode, however until the moment I haven’t make it works , could you help me to install the software?

I’m making tests in a Laptop Hp DV7 intel core i7, graphical card NVIDIA geforce GT 2GB and Ubuntu 18.04.  Here are lines that the terminal sends me:

manuel@manuel-HP-ENVY-dv7-Notebook-PC:/$ pygbe
Traceback (most recent call last):
  File "/usr/local/bin/pygbe", line 11, in <module>
    load_entry_point('PyGBe==0.3.1+26.g9297316', 'console_scripts', 'pygbe')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pygbe/main.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/gmres.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/matrixfree.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/tree/FMMutils.py", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyGBe-0.3.1+26.g9297316-py2.7-linux-x86_64.egg/pygbe/tree/multipole.py", line 99
    def multipole_c(K: 'double *', V: 'double *', M: 'double *', Md: 'double *', dxa: 'double *', dya: 'double *', dza: 'double *', index: 'int *', P: 'int', kappa: 'double', Nm: 'int', LorY: 'int') -> "void":
                     ^
SyntaxError: invalid syntax

Regards

Manuel Ruiz

**Comment by Marr575** [comment]
Hi, I have installed the python 3 but pygbe, (I think) is trying to use the python 2.7, mmmmm Do I need to uninstall python 2.7 and then reinstall only 3?

**Comment by ncclementi** [comment]
@Marr575 when you installed python 3 and the other dependencies, did you use anaconda or miniconda? If so, you probably downloaded that somewhere in your home. If you want pygbe and pycuda to look there for the dependencies you need to add that to your `.bashrc` for example if you installed miniconda the line in your bashrc that you need to add will look something like:
`export PATH="/home/username/miniconda3/bin:$PATH"`  depending where you downloaded miniconda.

**Comment by Marr575** [comment]
Hi I installed anaconda, and yes I downloaded to Download folder. I going to add the line that you say, just for curiosity do you speak Spanish?

**Comment by ncclementi** [comment]
Ok, then check the full path of your anaconda3/bin folder and then add in your `.bashrc`
`export PATH="full_path_of_anaconda3/bin:$PATH"` . After that you'll need to restart the terminal, and if you installed pycuda and all the other dependencies using python 2 you'll need to go over that again.
I'd recommend using a conda environment.

Regarding the Spanish, I do speak it but I'd prefer to maintain the conversation in English since that way most people can learn from your issue. However, if you need us to translate something, let us know and we will happily do it.

**Comment by ncclementi** [comment]
@Marr575 I'm not sure if I understand your problem. You said you got the same error, so it is still reading python 2.7? There might be some problem with the path you set. 
 Also, when I mentioned to install pycuda and the other dependencies again I meant the ones in the installation guides not reinstalling anaconda and cuda drivers. Pycuda and cuda are not the same thing. However you need cuda drivers working before proceeding to install Pycuda.

If you are having problems installing cuda drivers, there are usually tests provided by nvidia that you can try and check to make sure that it works. Also in the link you provided, you are following installations for Ubuntu 16.04 and you have 18.04 that can be a problem.

**Comment by Marr575** [comment]
do you have a video of how to install Pygbe?

**Comment by cdcooper84** [comment]
Hi @Marr575, it might be easier to just use the Docker container. This downloads everything you need to try pygbe in your Docker environment, and that way you're sure you have everything with the right version. If you are not able to install CUDA, you can still run pygbe on straight Docker. 

Download and install Docker from https://hub.docker.com/editions/community/docker-ce-server-ubuntu, then open the Docker terminal to run:
`docker build --tag=pygbe:master .`
`docker run --name=pygbe -it pygbe:master /bin/bash`

To go into pygbe's Docker container do 
`docker restart pygbe`
`docker exec -it pygbe /bin/bash`
`cd opt/pygbe/pygbe-master`

This should work. Let me know if you try it out.

**Comment by Marr575** [comment]
Hi I think I`m very close to install the software, however I still have problems. When I try to install pycuda the computer sends me these lines:

src/wrapper/wrap_cudadrv.cpp: In function ‘void init_module__driver()’:
src/wrapper/wrap_cudadrv.cpp:850:26: error: ‘CU_TARGET_COMPUTE_10’ was not declared in this scope
     .value("COMPUTE_10", CU_TARGET_COMPUTE_10)
                          ^
src/wrapper/wrap_cudadrv.cpp:851:26: error: ‘CU_TARGET_COMPUTE_11’ was not declared in this scope
     .value("COMPUTE_11", CU_TARGET_COMPUTE_11)
                          ^
src/wrapper/wrap_cudadrv.cpp:852:26: error: ‘CU_TARGET_COMPUTE_12’ was not declared in this scope
     .value("COMPUTE_12", CU_TARGET_COMPUTE_12)
                          ^
src/wrapper/wrap_cudadrv.cpp:853:26: error: ‘CU_TARGET_COMPUTE_13’ was not declared in this scope
     .value("COMPUTE_13", CU_TARGET_COMPUTE_13)
                          ^
error: command 'gcc' failed with exit status 1
Makefile:6: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 1

I want to try with the normal installation first if I cannot, I will try it with Docker

some ideas of why this is happening to me?

Regards

Manuel Ruiz

**Comment by ncclementi** [comment]
@Marr575 it seems there is a problem with your gcc compiler. I think you need to check which gcc you have and how it's been installed. I think in the latest version of `gcc` the name is `gcc5` or something like that. If the version of pycuda you are trying to install is looking for something called gcc and in you machine figures under a different name it won't find it. 

On the other side, the NVIDIA card you have is a graphic card and it doesn't handle double precision, therefore you won't be able to use the GPU to run pygbe.

**Comment by Marr575** [comment]
Well at the end I could install it in Ubuntu 18, runs, but only with the CPU not with the GPU =). Now I´m playing with the software, do you have a thesis or something that explain with more detail how to use the software? I have already read the README files and the website.

**Comment by ncclementi** [comment]
@Marr575 Glad you made it work and  yes it won't run with the GPU because of the type of GPU you have. Where you able to run the examples, at least the smallest ones? 
In the documentation, in the "Run pygbe " section there is an explanation on how to set your own cases. If you want to understand more about the algorithm, you can read the papers at the end of the README and complement the reading with @cdcooper84 thesis that can be found [here](https://open.bu.edu/handle/2144/15650). If you want to get into more specifics of what each part of the code does, you can read the code specific documentation, at the end of the software webpage http://barbagroup.github.io/pygbe/docs/ .

**Comment by Marr575** [comment]
Hi again

In this moment I’m doing the examples of pygbe, one question, in the example of 1PGBmut_sensor, how the files that inside of the geometry folder where generated?

Regards

**Comment by ncclementi** [comment]
HI @Marr575 , all the examples protein meshes were generated with MSMS, but recently we tried NanoShaper which resulted better for us. The meshes of the spheres and bricks where generated with scripts. All the information about it is in the documentation, http://barbagroup.github.io/pygbe/docs/mesh_pqr_setup.html

**Comment by Marr575** [comment]
Hi again

I`m doing the examples. in the example 1PGBmut_sensor there is a file named:
sensor_100x10x100_d02_-4e-5-4e-5-4e-5-4e-5-4e-5-4e-5.phi0
inside there is this number: -4.000000000000000327e-05, from where it comes?

Regards

**Comment by Marr575** [comment]
and another question, I’m trying to do the calculations with the protein alone 1PGB, for that purpose I removed the files of the sensor and erased the lines of the sensor in the .config file, but at the moment of run pygbe this sends me an error, what I’m doing wrong?

Generate interaction list
Traceback (most recent call last):
  File "/home/manuel/.conda/envs/pygbe/bin/pygbe", line 11, in <module>
    load_entry_point('PyGBe==0.3.1+26.g9297316', 'console_scripts', 'pygbe')()
  File "/home/manuel/.conda/envs/pygbe/lib/python3.6/site-packages/PyGBe-0.3.1+26.g9297316-py3.6-linux-x86_64.egg/pygbe/main.py", line 330, in main
    generateList(surf_array, field_array, param)
  File "/home/manuel/.conda/envs/pygbe/lib/python3.6/site-packages/PyGBe-0.3.1+26.g9297316-py3.6-linux-x86_64.egg/pygbe/tree/FMMutils.py", line 570, in generateList
    surf_array[s_src], surf_array[s_tar], CJ, CI,
IndexError: list index out of range

**Comment by ncclementi** [comment]
@Marr575 For the case of the sensor, you need to define the charge on the sensor, but the coder works withe potentials. As the documentations points out, here is the script used to create that file and an example. https://github.com/barbagroup/pygbe/blob/master/preprocessing_tools/generate_phi0.py

Regarding "for that purpose I removed the files of the sensor and erased the lines of the sensor in the .config file," you have to make sure that the surfaces are defined as needed, and the rest of the parameters too. For example, if you remove the sensor, then `Nchild` and `children` for the medium are different. You can read about the parameters in the documentation too. http://barbagroup.github.io/pygbe/docs/input_format.html 
You can also check the other examples config files and see how they are structured.  

Last but not least, since the subject of this issue was installation related, I would like to close it after this comment. You are more than welcome to open other ones if you need it.
